### ISSUE TITLE
DoS writeup

### ISSUE THREAD

**Issue by b-mueller** [trailofbits/not-so-smart-contracts#24]
Hi guys,

In the Denial-of-Service section it says "contracts that bulk perform transactions or updates using a for loop can be DoS'd if a call to another contract or send fails during the loop.".

AFAIK `send()` returns false if the call fails which means the loop would keep running. On the other hand, `transfer()` would propagate exceptions and cause a revert.

In the [example](https://github.com/trailofbits/not-so-smart-contracts/blob/master/denial_of_service/list_dos.sol):

```
contract CrowdFundSafe {
  address[] private refundAddresses;
  mapping(address => uint) public refundAmount;
  uint256 nextIdx;
  
  function refundSafe() public {
    uint256 i = nextIdx;
    while(i < refundAddresses.length && msg.gas > 200000) {
      refundAddresses[i].send(refundAmount[i]);
      i++;
    }
    nextIdx = i;
  }
}
```

IMO:

- `refundAddresses[I].send` failing would not cause the contract to revert (even using this pattern of has other issues, such as failing to notice when a user wasn't refunded successfully);

- If `transfer()` was used instead of send, a malicious contract could revert the call by throwing an exception in its fallback function;

- If `call().value()` was used to refund, a malicious contract could use up all gas;

- The other DOS vector would be to cause the list of funders to be to long, perhaps by sending small amounts of ETH from thousands of different addresses.

Note that I haven't actually tested any of this :)

**Comment by blperez01** [comment]
You are definitely correct that these `send`'s should be `transfer`'s. In the `refundSafe()` function, having a long list of funders would actually not cause the execution to revert because the `while` loop checks that `msg.gas > 200000` before each loop. It uses the index `i` to track where in the list it is so that if it runs out of gas the contract can resume the refund later.
