### ISSUE TITLE
Strange description in "missing constructor" section

### ISSUE THREAD

**Issue by b-mueller** [trailofbits/not-so-smart-contracts#25]
From [Missing Constructor](https://github.com/trailofbits/not-so-smart-contracts/tree/master/missing_constructor): "If the constructor of a smart contract is not present (or not spelled the same way as the contract name), it is callable by anyone."

IMO this doesn't make 100% sense. If the constructor is not present then it just means that state vars aren't initialized, not that is callable by anyone (something that's not present can't be called). 

Perhaps this describes the issue more accurately:

**Wrongly named constructor**: A function *intended* to be a constructor is named wrongly, which causes it to end up in the runtime bytecode instead of being a constructor.

**Comment by blperez01** [comment]
Thanks for the feedback! Agree that "Missing Constructor" might not be the best name for this vulnerability. Will change.
